### ISSUE TITLE
Header content isn't cenetered with page content

### ISSUE THREAD

**Issue by bhavanvir** [Qoaba/qoaba-frontend#31]
Suggestion: left-justify the centre-most controls

**Comment by alexwholland** [comment]
I think this is a good idea, but we should look into adding some padding on both the right and left side. Leetcode as reference:
<img width="1832" alt="Screen Shot 2023-08-17 at 8 45 06 PM" src="https://github.com/Qoaba/qoaba-frontend/assets/64433812/b71e680e-8f93-4222-a9cb-49902ed28de6">

**Comment by bhavanvir** [comment]
Header content was left-justified in #37, further tweaking can be done in the future
